name = "wiki-redirect"
main = "src/worker.js"
compatibility_date = "2025-03-16"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"
workers_dev = true

[observability]
enabled = true
